version: '3.8'

services:
  app:
    image: karthikeyanthiagarajan/guest-management-system:${APP_VERSION:-latest}
    container_name: guestmanagement_app
    ports:
      - "8000:8000"
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - sqlite_data:/guestmanagement/db.sqlite3
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP protocol port
      - "15672:15672" # Management UI port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  sqlite_data:
  rabbitmq_data: