# Generated by Django 5.2.17 on 2026-08-26 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("employee", "Employee"),
                    ("guest", "Guest"),
                ],
                default="guest",
                max_length=255,
            ),
        ),
    ]
