# Generated by Django 5.2.17 on 2026-08-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("iam", "0002_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("ADMIN", "Admin"),
                    ("EMPLOYEE", "Employee"),
                    ("RECEPTIONIST", "Receptionist"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
