# Generated by Django 5.2.17 on 2026-09-01 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="visit",
            name="guest",
        ),
        migrations.AddField(
            model_name="guest",
            name="identification_number",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="guest",
            name="identification_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("AADHAAR", "Aadhaar"),
                    ("PASSPORT", "Passport"),
                    ("DRIVING_LICENSE", "Driving License"),
                ],
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visit",
            name="invitation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="visits",
                to="gms.invitation",
            ),
        ),
    ]
