# Generated by Django 5.2.17 on 2026-09-01 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gms", "0002_remove_visit_guest_guest_identification_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="expected_departure",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="invitation_code",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="invitation",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=255,
            ),
        ),
    ]
